Adding country-based rule for firewall
alireza0/alireza0.github.io pull request #1
Opened 2023-09-16 23:00 UTC by mmrabbani

سلام
دو پیشنهاد تنظیم فایروال را در قالب یک بند قرار دادم.

من نوشتم که تنظیم فایروال بر اساس کشور در داخل سرور سخت است. چون به شخصه راه راحتی نمی‌شناختم. اگر راهی می‌شناسید، می‌توانید آن بخش را ادیت کنید.

2023-09-17 20:51 UTC, alireza0 requested changes
درود بر شما
ممنونم از همکاری شما
نکته خوبی رو اشاره کردین.
ببخشید که کمی سخت میگیرم.
لطفا این بخش ها رو تصحیح بفرمایید

2023-09-17 20:51 UTC, alireza0 commented on content/fa/docs/security/firewall.md
> +### ۴. محدود کردن ارتباط سرور با ایران
بهتره به شکل کلی نوشته بشه: محدود کردن ارتباط از یک کشور

2023-09-17 20:51 UTC, alireza0 commented on content/fa/docs/security/firewall.md
> +اگر کانفیگ را به صورت رایگان پخش می‌کنید، می‌توانید فایروال را به نحوی تنظیم کنید که برای پورت فیلترشکن، تنها امکان اتصال از IP ایران وجود داشته باشد. چون لیست IP ایران کاملا شفاف و مشخص نیست، تعریف
۱. اسم هایی مانند اسم کشور و فیلترشکن بهتره استفاده نشه!
۲. مشکل تعریف همه IP های ایران اینه که از عهده یک سرور کوچک بر نمیاد و بهتره روی فایروالهای بزرگ و یا کلاد ها باشه
۳. سرویس CDN به این مدل ربطی نداره و غلط مصطلح شده. بهتره واژه درستش که همون سرویس ابری یا پراکسی ابری هست رو استفاده کنیم.

2023-09-18 07:51 UTC, mmrabbani commented on content/fa/docs/security/firewall.md
> +اگر کانفیگ را به صورت رایگان پخش می‌کنید، می‌توانید فایروال را به نحوی تنظیم کنید که برای پورت فیلترشکن، تنها امکان اتصال از IP ایران وجود داشته باشد. چون لیست IP ایران کاملا شفاف و مشخص نیست، تعریف
در مورد بند ۲ و ۳ با شما موافقم. ولی عدم استفاده از اسم کشور، ممکنه مخاطب عام رو گیج کنه. البته که نهایت شما دسترسی تغییر در pull را دارید و باید شما با این موضوع اوکی باشید تا merge شود

2023-09-19 22:45 UTC, alireza0 commented on content/fa/docs/security/firewall.md
> +اگر کانفیگ را به صورت رایگان پخش می‌کنید، می‌توانید فایروال را به نحوی تنظیم کنید که برای پورت فیلترشکن، تنها امکان اتصال از IP ایران وجود داشته باشد. چون لیست IP ایران کاملا شفاف و مشخص نیست، تعریف
سپاسگزارم

2023-09-19 22:45 UTC, merged